version: '3.9'

services:
  backend:
    build: ./backend
    # network_mode: "host"
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./db_data:/db_data
      - ./Data:/Data

    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      ./.env
  frontend:
    build: ./app
    ports:
      - "3000:80"
    depends_on:
      - backend
    # volumes:
    #   - ./app:/usr/share/nginx/html
  mind:
    build: ./src
    user: root
    volumes:
      - ./Data:/Data
    ports:
      - "93:93"
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      ./.env
